### ISSUE TITLE
Functions to access to numerator and denomerator of tf

### ISSUE THREAD

**Issue by baggepinnen** [mfalt/Control.jl#12]
e.g.  `numerator = num(G)`
and `num,denom = poly(G)`

**Comment by mfalt** [comment]
What would be the result of this, a Transferfunction, or a Polinomial? And how do we handle the fact that transferfunctions by default are MIMO systems, only allow it for siso systems?

**Comment by baggepinnen** [comment]
I often find the fact that all TFs are MIMO systems confusing. This is not the case in matlab, and it causes a lot of unexpected behaviour. The boxing and unboxing required to convert between scalars and arrays is very confusing in the beginning, and annoying in the end.  Students with little or no julia experience will not find the error messages very helpful in the beginning.

The result could be an array of polynomials in the MIMO case. In the siso case, I would like a polynomial, not a one element array of polynomials, which I acknowledge is a strange special case behavior.

**Comment by mfalt** [comment]
This issue was moved to JuliaControl/Control.jl#20
