### ISSUE TITLE
ss(G) error

### ISSUE THREAD

**Issue by baggepinnen** [mfalt/Control.jl#2]
sys = ss(G)
ERROR: MethodError: `convert` has no method matching convert(::Type{Control.SisoTf}, ::Control.Poly{Float64}, ::Control.Poly{Float64})
This may have arisen from a call to the constructor Control.SisoTf(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, ::T)
 in siso_tf_to_ss at /local/home/fredrikb/.julia/v0.4/Control/src/types/tf2ss.jl:40
 in convert at /local/home/fredrikb/.julia/v0.4/Control/src/types/tf2ss.jl:12
 in ss at /local/home/fredrikb/.julia/v0.4/Control/src/types/statespace.jl:100

**Comment by mfalt** [comment]
Fixed in 2219b35, could @baggepinnen verify this for your case too? (I wasn't able to recreate it for SisoRational)

**Comment by baggepinnen** [comment]
Seems to be working now
