### ISSUE TITLE
margin() should compute delay margin

### ISSUE THREAD

**Issue by baggepinnen** [mfalt/Control.jl#21]
Currently, only gain and phase margins are computed, delay margin is also of interest

**Comment by baggepinnen** [comment]
Should be priority since it's needed in handin 2 :D

**Comment by baggepinnen** [comment]
Margin does not give same answer as matlabs margin, not even close

**Comment by baggepinnen** [comment]
separate delaymargin function added in branch pid

**Comment by mfalt** [comment]
This issue was moved to JuliaControl/Control.jl#18
