### ISSUE TITLE
bug in evalfr

### ISSUE THREAD

**Issue by baggepinnen** [mfalt/Control.jl#27]
evalfr and  freqresp does not yield the same result, this caused bug in margin. Bug has been repaired by switching to freqresp, but evalfr should be fixed

**Comment by mfalt** [comment]
Is this for continuous or discrete systems?

**Comment by baggepinnen** [comment]
At least for discrete

**Comment by baggepinnen** [comment]
The problem was not in evalfr, rather in how it was called. Problem solved in branch pid for all places I could find it

**Comment by mfalt** [comment]
This issue was moved to JuliaControl/Control.jl#14
