### ISSUE TITLE
zpkdata implementation flawed when considering discrete systems

### ISSUE THREAD

**Issue by baggepinnen** [mfalt/Control.jl#28]
The code below, is wrong, both for continuous and discrete systems
```
function _zpk_kern(s::SisoRational)
  return roots(s.num), roots(s.den), s.num[1]/s.den[1]
end
```

this fix works for continuous
```
function _zpk_kern(s::SisoRational)
  return roots(s.num), roots(s.den), s.num[end]/s.den[end]
end
```
but not for discrete, since SisoRational does not hold info regarding cont/discrete

**Comment by baggepinnen** [comment]
mostly fixed in pid branch

**Comment by mfalt** [comment]
How do you define the `k` in discrete time? I thought it would still be k*(z^n+b1z^{n-1}...bn)/(z^n+a1z^{n-1}...an).

**Comment by mfalt** [comment]
This issue was moved to JuliaControl/Control.jl#13
