### ISSUE TITLE
rlocus must track roots

### ISSUE THREAD

**Issue by baggepinnen** [mfalt/Control.jl#32]
the roots are sometimes mixed up in rlocus, there must be some intelligence to sort the roots such that the trajectories are continuous

**Comment by mfalt** [comment]
One alternative is to not draw lines, but simply plotting dots at each point, but this might not be a great solution. The best solution is probably to
```
for each K
   for each pole
        match the pole to the closest pole, in absolute distance at the previous k.
```
Something very similar to the minreal code.

**Comment by baggepinnen** [comment]
Dots do not solve the problem since the color is of importance. The for-loop approach deserves a try tomorrow

**Comment by mfalt** [comment]
We should probably be careful with using minreal when calculating the poles though, or we might run into problems when the poles approach the zeros.

**Comment by baggepinnen** [comment]
Yes, I removed minreal from rlocus in last commit

**Comment by mfalt** [comment]
We should probably do something like
```
G = minreal(G)
nump = numpoly(P)
denp = denpoly(P)
allroots = [roots(nump + k*denp) for k in K]
```
instead of using the normal roots function. (I invented the numpoly function here, so that nump and denp are simple polynomials)

**Comment by mfalt** [comment]
This issue was moved to JuliaControl/Control.jl#11
